### ISSUE TITLE
The tab menu is not responsive

### ISSUE THREAD

**Issue by Sivakajan-tech** [Sivakajan-tech/graph_oil_price#2]

**Comment by Dcode2100** [comment]
If this issue is open can you assign this to me

**Comment by Sivakajan-tech** [comment]
https://github.com/Sivakajan-tech/graph_oil_price/blob/ef11a3d095742b4ae2ad91edd414bc1a8c12c5ec/datavisualization.py#L96-L102
no problem

    q.page['navigator'] = ui.tab_card(
        box='navigator',
        items=[
            ui.tab(name='table', label="Table View"),
            ui.tab(name='plot', label="Plot View"),
        ]
    )
